# DigitalOcean App Platform Configuration
# 
# This file defines the App Platform application configuration for
# the Resilion Enrichment Pre-Loader project.
#
# Updated for Milestone 6: CI/CD, Deployment & Documentation

name: resilion-enrichment-preloader
region: nyc

services:
- name: web
  source_dir: /
  github:
    repo: HGS-RD/resilion-enrichment-poc
    branch: main
    deploy_on_push: true
  run_command: cd apps/web && npm start
  build_command: ./build.sh
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  routes:
  - path: /
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  # Application Configuration
  - key: NODE_ENV
    value: production
  - key: LOG_LEVEL
    value: info
  - key: PORT
    value: "3001"
  
  # Database Configuration
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  
  # Vector Database Configuration
  - key: PINECONE_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PINECONE_INDEX_NAME
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PINECONE_INDEX_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PINECONE_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: PINECONE_DIMENSIONS
    value: "1024"
  - key: PINECONE_METRIC
    value: "cosine"
  - key: PINECONE_CLOUD
    value: "aws"
  - key: PINECONE_REGION
    value: "us-east-1"
  
  # LLM API Keys
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: XAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ANTHROPIC_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  
  # External API Configuration
  - key: BING_NEWS_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SEC_EDGAR_USER_AGENT
    value: "Resilion Enrichment Service contact@resilion.com"
  
  # Application Features
  - key: ENABLE_FINANCIAL_DOCUMENTS
    value: "true"
  - key: ENABLE_NEWS_ENRICHMENT
    value: "true"
  - key: ENABLE_TIER_PROCESSING
    value: "true"
  
  # Performance Configuration
  - key: MAX_CONCURRENT_JOBS
    value: "5"
  - key: JOB_TIMEOUT_MINUTES
    value: "30"
  - key: MAX_RETRY_ATTEMPTS
    value: "3"

# Database Configuration
databases:
- name: resilion-preloader-db
  engine: PG
  version: "15"
  production: true
  size: basic

# Static Site Configuration (if needed for documentation)
static_sites:
- name: docs
  source_dir: docs
  github:
    repo: HGS-RD/resilion-enrichment-poc
    branch: main
    deploy_on_push: true
  build_command: echo "Documentation site"
  output_dir: /
  routes:
  - path: /docs
